### ISSUE TITLE
Thank you :-)

### ISSUE THREAD

**Issue by alexanderad** [topic2k/pygcgen#17]
Hello @topic2k, just found your port from Ruby and just wanted to say Thank you!

We have python-only [and slim] infrastructure and incorporating Ruby and gems and all the other Ruby related things of _proper_ version into our CI just to get the Changelog built was a _huge pain_.

Now it is just 
```
RUN pip install --no-cache-dir pygcgen
```
In our dockerfile for CI.

Thanks once again. This issue is `wontfix` please.

**Comment by topic2k** [comment]
Thank you @alexanderad. I made the port because i wasn't able to get the ruby version running and because i had some fun doing it. Never thought that someone other then me will find it usefull. 😄
