### ISSUE TITLE
Tag label headings are H1 instead of H2

### ISSUE THREAD

**Issue by hakjoon** [topic2k/pygcgen#27]
First of all thank you for this port.  I really like the original ruby version but being a python shop this is much easier to integrate into out workflows.

One difference I noticed when trying to move existing projects to this port is that the label headers are being set as H1s instead of H2s for example 

For Example
```markdown
# Change Log

# [5.1.1](https://github.com/foo/bar/tree/5.1.1) (2018-05-22)
```

The ruby version uses H2s (`## ...`) and it does seem like more logical HTML since `# Change Log` is an H1.

That version looks like
```markdown
# Change Log

## [5.1.1](https://github.com/foo/bar/tree/5.1.1) (2018-05-22)
```

Is there any to configure this? 

Again thanks for the port.

**Comment by topic2k** [comment]
You are right. To be closer to the original ruby version i changed it. Thanks for the detailed report.
